# Generated by Django 4.0.1 on 2022-01-15 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UUID_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
