# Generated by Django 4.0.1 on 2022-01-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uuid_generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uuid_table",
            options={"ordering": ["-key"]},
        ),
        migrations.RenameField(
            model_name="uuid_table",
            old_name="created_at",
            new_name="key",
        ),
    ]
