# Generated by Django 4.0.1 on 2022-01-15 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("uuid_generator", "0002_alter_uuid_table_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uuid_table",
            name="key",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
