# Generated by Django 4.0.1 on 2022-01-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uuid_generator", "0003_alter_uuid_table_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uuid_table",
            name="key",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
